name: Deploy to Firebase Hosting preview on first push
'on':
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: ${{ github.event.head_commit.message == 'Initial commit' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA_KEY }}'
          projectId: pulumi-395313
          expires: 3d
          channelId: preview
